/** SDK 家族 CLI Adapter 共用的输出与行为常量。 */
export const OPERATION_RESULT_GUARDRAIL = [
  'Remote operation guardrail:',
  '- When the user asks you to create, modify, delete, move, or inspect local files or run shell commands, use the available tools to actually do or verify it.',
  '- Never claim a filesystem or shell operation succeeded unless you received a successful tool result in this turn.',
  '- If a required tool was not called, was denied, or failed, say the operation was not completed.',
].join('\n')

export const EMPTY_VISIBLE_RESULT_MESSAGE = '本轮没有生成可见回复，请重试。'

/** SDK 名称不同但语义一致的只读工具/permission，统一按小写匹配。 */
export const READ_ONLY_TOOL_NAMES = new Set([
  'read',
  'glob',
  'grep',
  'websearch',
  'webfetch',
  'listmcpresources',
  'readmcpresourcedir',
  'readmcpresource',
  'projects',
])

/** 所有 CLI 共用的保守只读 shell 命令；仅单条、无组合操作时自动放行。 */
export const READ_ONLY_SHELL_COMMANDS = new Set([
  'cat',
  'df',
  'dir',
  'du',
  'echo',
  'file',
  'free',
  'grep',
  'head',
  'id',
  'jq',
  'locate',
  'ls',
  'netstat',
  'printenv',
  'ps',
  'pwd',
  'readlink',
  'realpath',
  'rg',
  'ripgrep',
  'stat',
  'systeminfo',
  'tail',
  'tasklist',
  'tree',
  'type',
  'uname',
  'ver',
  'wc',
  'where',
  'which',
  'whoami',
])

/** Windows PowerShell 查询 cmdlet/常用只读 alias。 */
export const READ_ONLY_POWERSHELL_COMMANDS = new Set(
  [
    'compare-object',
    'convertfrom-json',
    'convertto-json',
    'format-hex',
    'format-list',
    'format-table',
    'gc',
    'gci',
    'gcm',
    'gcs',
    'gdr',
    'ghy',
    'gi',
    'gl',
    'gm',
    'gp',
    'gps',
    'gs',
    'gv',
    'measure-object',
    'out-string',
    'resolve-path',
    'select-object',
    'select-string',
    'split-path',
    'test-path',
    'write-output',
    'get-acl',
    'get-alias',
    'get-childitem',
    'get-child-item',
    'get-ciminstance',
    'get-clipboard',
    'get-command',
    'get-computerinfo',
    'get-content',
    'get-culture',
    'get-date',
    'get-eventlog',
    'get-filehash',
    'get-help',
    'get-history',
    'get-host',
    'get-item',
    'get-itemproperty',
    'get-location',
    'get-member',
    'get-module',
    'get-process',
    'get-psdrive',
    'get-psprovider',
    'get-random',
    'get-service',
    'get-timezone',
    'get-tracesource',
    'get-typeData',
    'get-variable',
    'get-winevent',
    'get-wmiobject',
  ].map(command => command.toLowerCase()),
)

export const READ_ONLY_GIT_SUBCOMMANDS = new Set([
  'blame',
  'cat-file',
  'count-objects',
  'describe',
  'diff',
  'diff-tree',
  'for-each-ref',
  'grep',
  'log',
  'ls-files',
  'ls-tree',
  'name-rev',
  'rev-parse',
  'shortlog',
  'show',
  'status',
])

export const VERSION_ONLY_COMMANDS = new Set([
  'bun',
  'claude',
  'deno',
  'nginx',
  'node',
  'npm',
  'opencode',
  'pm2',
  'python',
  'python3',
])
