/**
 * Drizzle migration reporting.
 *
 * Reads only Drizzle's own migration journal/table and migration SQL files so
 * deployment tooling can describe migrations that are actually about to run.
 */
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { sql } from 'drizzle-orm'
import type { Db } from './db'

export const DB_MIGRATION_REPORT_PREFIX = 'AI_CLI_HUB_DB_REPORT='

interface JournalEntry {
  when: number
  tag: string
}

interface Journal {
  entries: JournalEntry[]
}

export interface PendingMigration {
  tag: string
  changes: string[]
}

export interface DatabaseMigrationReport {
  applied: PendingMigration[]
}

/** Returns migrations newer than the latest migration recorded by Drizzle. */
export async function inspectPendingMigrations(
  db: Db,
  migrationsFolder = './drizzle',
): Promise<DatabaseMigrationReport> {
  const tableRows = await db.execute<{ name: string | null }>(
    sql`select to_regclass('drizzle.__drizzle_migrations')::text as "name"`,
  )
  let lastAppliedAt = Number.NEGATIVE_INFINITY
  if (tableRows[0]?.name) {
    const rows = await db.execute<{ createdAt: string | number | null }>(
      sql`select max("created_at") as "createdAt" from "drizzle"."__drizzle_migrations"`,
    )
    const value = Number(rows[0]?.createdAt)
    if (Number.isFinite(value)) lastAppliedAt = value
  }

  const folder = path.resolve(migrationsFolder)
  const journal = JSON.parse(await readFile(path.join(folder, 'meta', '_journal.json'), 'utf8')) as Journal
  const pending = journal.entries.filter(entry => entry.when > lastAppliedAt)
  return {
    applied: await Promise.all(
      pending.map(async entry => ({
        tag: entry.tag,
        changes: summarizeMigrationSql(await readFile(path.join(folder, `${entry.tag}.sql`), 'utf8')),
      })),
    ),
  }
}

/** Best-effort concise descriptions for the DDL/DML generated by Drizzle Kit. */
export function summarizeMigrationSql(source: string): string[] {
  const statements = source
    .split('--> statement-breakpoint')
    .map(statement => statement.replace(/\s+/g, ' ').trim().replace(/;$/, ''))
    .filter(Boolean)
  const changes = statements.map(summarizeStatement)
  return [...new Set(changes)]
}

function summarizeStatement(statement: string): string {
  const table = capture(
    statement,
    /(?:ALTER TABLE|CREATE TABLE|DROP TABLE|UPDATE|INSERT INTO|DELETE FROM)\s+([^\s(]+)/i,
  )
  const addColumn = capture(statement, /\bADD COLUMN\s+([^\s]+)/i)
  if (/^ALTER TABLE/i.test(statement) && addColumn) return `${cleanName(table)}：新增字段 ${cleanName(addColumn)}`
  const dropColumn = capture(statement, /\bDROP COLUMN\s+([^\s]+)/i)
  if (/^ALTER TABLE/i.test(statement) && dropColumn) return `${cleanName(table)}：删除字段 ${cleanName(dropColumn)}`
  const alterColumn = capture(statement, /\bALTER COLUMN\s+([^\s]+)/i)
  if (/^ALTER TABLE/i.test(statement) && alterColumn) return `${cleanName(table)}：修改字段 ${cleanName(alterColumn)}`
  const addConstraint = capture(statement, /\bADD CONSTRAINT\s+([^\s]+)/i)
  if (/^ALTER TABLE/i.test(statement) && addConstraint)
    return `${cleanName(table)}：新增约束 ${cleanName(addConstraint)}`
  const dropConstraint = capture(statement, /\bDROP CONSTRAINT\s+([^\s]+)/i)
  if (/^ALTER TABLE/i.test(statement) && dropConstraint)
    return `${cleanName(table)}：删除约束 ${cleanName(dropConstraint)}`
  if (/^CREATE TABLE/i.test(statement)) return `新增表 ${cleanName(table)}`
  if (/^DROP TABLE/i.test(statement)) return `删除表 ${cleanName(table)}`

  const typeName = capture(statement, /^(?:CREATE|DROP) TYPE\s+([^\s]+)/i)
  if (/^CREATE TYPE/i.test(statement)) return `新增类型 ${cleanName(typeName)}`
  if (/^DROP TYPE/i.test(statement)) return `删除类型 ${cleanName(typeName)}`

  const indexName = capture(statement, /^CREATE(?: UNIQUE)? INDEX\s+([^\s]+)/i)
  const indexTable = capture(statement, /\bON\s+([^\s(]+)/i)
  if (indexName) return `${cleanName(indexTable)}：新增索引 ${cleanName(indexName)}`
  const droppedIndex = capture(statement, /^DROP INDEX\s+([^\s]+)/i)
  if (droppedIndex) return `删除索引 ${cleanName(droppedIndex)}`

  if (/^UPDATE/i.test(statement)) return `${cleanName(table)}：更新数据`
  if (/^DELETE FROM/i.test(statement)) return `${cleanName(table)}：清理数据`
  if (/^INSERT INTO/i.test(statement)) return `${cleanName(table)}：写入数据`
  return '执行数据库结构或数据变更'
}

function capture(value: string, pattern: RegExp): string | null {
  return pattern.exec(value)?.[1] ?? null
}

function cleanName(value: string | null): string {
  if (!value) return '数据库'
  return value
    .split('.')
    .map(segment => segment.replace(/^"|"$/g, ''))
    .join('.')
}
