import type { InboundEmoji } from '../shared'

const EMOJI_INFO: Record<string, { name: string; keywords: string[] }> = {
  '😀': { name: 'grinning face', keywords: ['happy', 'smile'] },
  '😁': { name: 'beaming face with smiling eyes', keywords: ['happy', 'grin', 'smile'] },
  '😃': { name: 'grinning face with big eyes', keywords: ['happy', 'smile'] },
  '😄': { name: 'grinning face with smiling eyes', keywords: ['happy', 'smile'] },
  '😆': { name: 'grinning squinting face', keywords: ['laugh', 'happy'] },
  '😇': { name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
  '🙂': { name: 'slightly smiling face', keywords: ['smile', 'friendly'] },
  '🙃': { name: 'upside-down face', keywords: ['sarcasm', 'silly'] },
  '😉': { name: 'winking face', keywords: ['wink', 'playful'] },
  '😅': { name: 'grinning face with sweat', keywords: ['relief', 'awkward', 'smile'] },
  '😂': { name: 'face with tears of joy', keywords: ['laugh', 'funny'] },
  '🤣': { name: 'rolling on the floor laughing', keywords: ['laugh', 'funny'] },
  '😊': { name: 'smiling face with smiling eyes', keywords: ['happy', 'warm'] },
  '😋': { name: 'face savoring food', keywords: ['delicious', 'food'] },
  '😎': { name: 'smiling face with sunglasses', keywords: ['cool', 'confident'] },
  '🥳': { name: 'partying face', keywords: ['celebrate', 'party'] },
  '😏': { name: 'smirking face', keywords: ['smug', 'flirt'] },
  '😍': { name: 'smiling face with heart-eyes', keywords: ['love', 'like'] },
  '😘': { name: 'face blowing a kiss', keywords: ['love', 'kiss'] },
  '🥰': { name: 'smiling face with hearts', keywords: ['love', 'affection'] },
  '🤩': { name: 'star-struck', keywords: ['excited', 'amazed'] },
  '😐': { name: 'neutral face', keywords: ['neutral', 'blank'] },
  '😑': { name: 'expressionless face', keywords: ['unimpressed', 'blank'] },
  '😶': { name: 'face without mouth', keywords: ['silent', 'speechless'] },
  '🫥': { name: 'dotted line face', keywords: ['invisible', 'awkward'] },
  '🤐': { name: 'zipper-mouth face', keywords: ['secret', 'silent'] },
  '🤨': { name: 'face with raised eyebrow', keywords: ['skeptical', 'question'] },
  '😭': { name: 'loudly crying face', keywords: ['crying', 'sad', 'overwhelmed'] },
  '😢': { name: 'crying face', keywords: ['sad', 'tear'] },
  '🥲': { name: 'smiling face with tear', keywords: ['bittersweet', 'emotional'] },
  '😞': { name: 'disappointed face', keywords: ['sad', 'disappointed'] },
  '😔': { name: 'pensive face', keywords: ['sad', 'thoughtful'] },
  '😟': { name: 'worried face', keywords: ['worried', 'concerned'] },
  '😕': { name: 'confused face', keywords: ['confused', 'uncertain'] },
  '🫤': { name: 'face with diagonal mouth', keywords: ['unsure', 'disappointed'] },
  '😣': { name: 'persevering face', keywords: ['struggling', 'frustrated'] },
  '😖': { name: 'confounded face', keywords: ['frustrated', 'confused'] },
  '😫': { name: 'tired face', keywords: ['tired', 'exhausted'] },
  '😩': { name: 'weary face', keywords: ['tired', 'distressed'] },
  '😤': { name: 'face with steam from nose', keywords: ['frustrated', 'triumph'] },
  '😠': { name: 'angry face', keywords: ['angry', 'mad'] },
  '😡': { name: 'pouting face', keywords: ['angry', 'mad'] },
  '🤬': { name: 'face with symbols on mouth', keywords: ['angry', 'swearing'] },
  '😱': { name: 'face screaming in fear', keywords: ['scared', 'shock'] },
  '😨': { name: 'fearful face', keywords: ['scared', 'anxious'] },
  '😰': { name: 'anxious face with sweat', keywords: ['anxious', 'stress'] },
  '😥': { name: 'sad but relieved face', keywords: ['relief', 'sad'] },
  '😓': { name: 'downcast face with sweat', keywords: ['sad', 'stress'] },
  '🤔': { name: 'thinking face', keywords: ['thinking', 'question'] },
  '🫡': { name: 'saluting face', keywords: ['respect', 'acknowledged'] },
  '🤗': { name: 'smiling face with open hands', keywords: ['hug', 'warm'] },
  '🤭': { name: 'face with hand over mouth', keywords: ['giggle', 'surprise'] },
  '🫢': { name: 'face with open eyes and hand over mouth', keywords: ['shock', 'surprise'] },
  '🤫': { name: 'shushing face', keywords: ['quiet', 'secret'] },
  '🤥': { name: 'lying face', keywords: ['lie', 'pinocchio'] },
  '🙄': { name: 'face with rolling eyes', keywords: ['annoyed', 'skeptical'] },
  '😬': { name: 'grimacing face', keywords: ['awkward', 'nervous'] },
  '😮': { name: 'face with open mouth', keywords: ['surprised', 'wow'] },
  '😯': { name: 'hushed face', keywords: ['surprised', 'quiet'] },
  '😲': { name: 'astonished face', keywords: ['surprised', 'amazed'] },
  '🥱': { name: 'yawning face', keywords: ['tired', 'sleepy'] },
  '😴': { name: 'sleeping face', keywords: ['sleep', 'tired'] },
  '🤤': { name: 'drooling face', keywords: ['want', 'food'] },
  '😈': { name: 'smiling face with horns', keywords: ['mischief', 'devil'] },
  '👿': { name: 'angry face with horns', keywords: ['angry', 'devil'] },
  '💩': { name: 'pile of poo', keywords: ['poop', 'funny'] },
  '🤡': { name: 'clown face', keywords: ['clown', 'silly'] },
  '👻': { name: 'ghost', keywords: ['spooky', 'halloween'] },
  '💀': { name: 'skull', keywords: ['death', 'dead'] },
  '🤖': { name: 'robot', keywords: ['bot', 'ai', 'machine'] },
  '👍': { name: 'thumbs up', keywords: ['approve', 'ok', 'good'] },
  '👎': { name: 'thumbs down', keywords: ['reject', 'bad', 'dislike'] },
  '👏': { name: 'clapping hands', keywords: ['applause', 'praise'] },
  '🙌': { name: 'raising hands', keywords: ['celebrate', 'success'] },
  '🤝': { name: 'handshake', keywords: ['agreement', 'deal'] },
  '🤞': { name: 'crossed fingers', keywords: ['hope', 'luck'] },
  '✌️': { name: 'victory hand', keywords: ['peace', 'win'] },
  '👋': { name: 'waving hand', keywords: ['hello', 'goodbye'] },
  '👌': { name: 'OK hand', keywords: ['ok', 'good'] },
  '💪': { name: 'flexed biceps', keywords: ['strong', 'effort'] },
  '🙏': { name: 'folded hands', keywords: ['thanks', 'please', 'pray'] },
  '❤️': { name: 'red heart', keywords: ['love', 'heart'] },
  '🧡': { name: 'orange heart', keywords: ['love', 'care'] },
  '💛': { name: 'yellow heart', keywords: ['love', 'friendship'] },
  '💚': { name: 'green heart', keywords: ['love', 'nature'] },
  '💙': { name: 'blue heart', keywords: ['love', 'trust'] },
  '💜': { name: 'purple heart', keywords: ['love', 'care'] },
  '🖤': { name: 'black heart', keywords: ['love', 'dark'] },
  '🤍': { name: 'white heart', keywords: ['love', 'peace'] },
  '💔': { name: 'broken heart', keywords: ['sad', 'heartbreak'] },
  '💯': { name: 'hundred points', keywords: ['perfect', 'score'] },
  '💤': { name: 'ZZZ', keywords: ['sleep', 'tired'] },
  '🔥': { name: 'fire', keywords: ['hot', 'great', 'urgent'] },
  '✨': { name: 'sparkles', keywords: ['magic', 'new'] },
  '⭐': { name: 'star', keywords: ['favorite', 'excellent'] },
  '🌟': { name: 'glowing star', keywords: ['excellent', 'special'] },
  '💡': { name: 'light bulb', keywords: ['idea', 'insight'] },
  '💥': { name: 'collision', keywords: ['impact', 'boom'] },
  '🎯': { name: 'bullseye', keywords: ['goal', 'target'] },
  '📌': { name: 'pushpin', keywords: ['important', 'pin'] },
  '📎': { name: 'paperclip', keywords: ['attachment', 'file'] },
  '📁': { name: 'file folder', keywords: ['folder', 'files'] },
  '📝': { name: 'memo', keywords: ['note', 'write'] },
  '🔍': { name: 'magnifying glass tilted left', keywords: ['search', 'inspect'] },
  '🔒': { name: 'locked', keywords: ['secure', 'private'] },
  '🔓': { name: 'unlocked', keywords: ['open', 'security'] },
  '⚙️': { name: 'gear', keywords: ['settings', 'configuration'] },
  '🛠️': { name: 'hammer and wrench', keywords: ['tools', 'fix'] },
  '🐛': { name: 'bug', keywords: ['bug', 'debug'] },
  '🧪': { name: 'test tube', keywords: ['test', 'experiment'] },
  '📊': { name: 'bar chart', keywords: ['metrics', 'statistics'] },
  '📈': { name: 'chart increasing', keywords: ['growth', 'up'] },
  '📉': { name: 'chart decreasing', keywords: ['decline', 'down'] },
  '🎉': { name: 'party popper', keywords: ['celebrate', 'success'] },
  '✅': { name: 'check mark button', keywords: ['done', 'success', 'yes'] },
  '❌': { name: 'cross mark', keywords: ['no', 'failed', 'cancel'] },
  '❓': { name: 'question mark', keywords: ['question', 'help'] },
  '❗': { name: 'exclamation mark', keywords: ['important', 'warning'] },
  '⚠️': { name: 'warning', keywords: ['warning', 'attention'] },
  '🚀': { name: 'rocket', keywords: ['launch', 'fast', 'deploy'] },
}

// `Extended_Pictographic` 是 ECMAScript 支持的 Unicode binary property；旧 IDE 语法检查器可能尚未识别它。
const EMOJI_RE = /\p{Extended_Pictographic}\uFE0F?/gu

function codePointLabel(emoji: string): string {
  return [...emoji].map(ch => `U+${(ch.codePointAt(0) ?? 0).toString(16).toUpperCase()}`).join(' ')
}

export function normalizeEmojis(text: string): InboundEmoji[] {
  const found = new Map<string, InboundEmoji>()
  for (const match of text.matchAll(EMOJI_RE)) {
    const emoji = match[0]
    const info = EMOJI_INFO[emoji] ?? { name: `emoji ${codePointLabel(emoji)}`, keywords: ['emoji'] }
    found.set(emoji, { emoji, name: info.name, keywords: info.keywords })
  }
  return [...found.values()]
}
